In [13]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
arr1.size

# find the data type 
print(arr1.dtype)
print(type(arr1))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>

In [20]:
# Multi dimensional array
arr2 = np.array([(1,2,3,4),(1,2,3.5,5)],dtype=complex)
print(arr2)
print(arr2.dtype)

[[1. +0.j 2. +0.j 3. +0.j 4. +0.j]
 [1. +0.j 2. +0.j 3.5+0.j 5. +0.j]]
complex128

In [26]:
# find the range in numpy
print(np.arange(10,30,10))
print(np.arange(10,30,5))
print(np.arange(10,30,1))

[10 20]
[10 15 20 25]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]

In [27]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [32]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4])

arr1 + arr2

array([3, 5, 7])

In [35]:
# Dimention
arr1 = np.array([[1,2,3],[4,5,6]])
arr1.ndim

2

In [37]:
# Shape
arr1.shape

(2, 3)

# Pandas

In [1]:
import pandas as pd
import numpy as np

arr = np.array(['a','b','c','d'])
pd.Series(arr)

0    a
1    b
2    c
3    d
dtype: object

In [6]:
data = {
    "student":['Rohan',"vishwa","Pradeep"],
    "age":[22,24,23]
}

df = pd.DataFrame(data)
sr = pd.Series(data)
print(df)
#   student  age
# 0    Rohan   22
# 1   vishwa   24
# 2  Pradeep   23

print(sr)
# student    [Rohan, vishwa, Pradeep]
# age                    [22, 24, 23]

   student  age
0    Rohan   22
1   vishwa   24
2  Pradeep   23
student    [Rohan, vishwa, Pradeep]
age                    [22, 24, 23]
dtype: object

In [5]:
# finding the version of the pandas
print(pd.__version__)

2.2.3

In [9]:
# Create the label in the series and Dataframe
df = pd.DataFrame(data,index=['a','b','c'])
print(df)

# student  age
# a    Rohan   22
# b   vishwa   24
# c  Pradeep   23

   student  age
a    Rohan   22
b   vishwa   24
c  Pradeep   23

In [20]:
# Read the csv file using pandas
import pandas as pd

data = pd.read_csv('students.csv')
# print(data.to_string(),end="\n")
print(data)

# print the data in DataFrame formate
print("Data formate : ",end="\n")
print(pd.DataFrame(data))


print("Series")
print(pd.Series(data["Name"]))

   StudentID    Name  Age  Gender Department  Marks  Attendance       City
0          1   Rohan   21    Male        CSE     90          95  Bangalore
1          2    John   22    Male        ECE     85          88     Mumbai
2          3   Alice   20  Female         ME     95          92      Delhi
3          4     Bob   23    Male        CSE     78          85    Chennai
4          5    Emma   21  Female        ECE     88          90  Hyderabad
5          6   David   22    Male        CSE     92          97       Pune
6          7  Sophia   20  Female         ME     81          89    Kolkata
7          8    Liam   21    Male        CSE     87          93  Bangalore
8          9  Olivia   22  Female        ECE     94          96     Mumbai
9         10    Noah   23    Male         ME     76          84      Delhi
Data formate :
   StudentID    Name  Age  Gender Department  Marks  Attendance       City
0          1   Rohan   21    Male        CSE     90          95  Bangalore
1          2    John   22    Male        ECE     85          88     Mumbai
2          3   Alice   20  Female         ME     95          92      Delhi
3          4     Bob   23    Male        CSE     78          85    Chennai
4          5    Emma   21  Female        ECE     88          90  Hyderabad
5          6   David   22    Male        CSE     92          97       Pune
6          7  Sophia   20  Female         ME     81          89    Kolkata
7          8    Liam   21    Male        CSE     87          93  Bangalore
8          9  Olivia   22  Female        ECE     94          96     Mumbai
9         10    Noah   23    Male         ME     76          84      Delhi
Series
0     Rohan
1      John
2     Alice
3       Bob
4      Emma
5     David
6    Sophia
7      Liam
8    Olivia
9      Noah
Name: Name, dtype: object

# Reading Json file

In [23]:
import pandas as pd
data = pd.read_json('students.json')
print(pd.DataFrame(data))

   StudentID    Name  Age  Gender Department  Marks  Attendance       City
0          1   Rohan   21    Male        CSE     90          95  Bangalore
1          2    John   22    Male        ECE     85          88     Mumbai
2          3   Alice   20  Female         ME     95          92      Delhi
3          4     Bob   23    Male        CSE     78          85    Chennai
4          5    Emma   21  Female        ECE     88          90  Hyderabad
5          6   David   22    Male        CSE     92          97       Pune
6          7  Sophia   20  Female         ME     81          89    Kolkata
7          8    Liam   21    Male        CSE     87          93  Bangalore
8          9  Olivia   22  Female        ECE     94          96     Mumbai
9         10    Noah   23    Male         ME     76          84      Delhi

In [27]:
# head() : This is used for displaying the specific number of rows from a file or data top to bottom.

print(data.head())

   StudentID   Name  Age  Gender Department  Marks  Attendance       City
0          1  Rohan   21    Male        CSE     90          95  Bangalore
1          2   John   22    Male        ECE     85          88     Mumbai
2          3  Alice   20  Female         ME     95          92      Delhi
3          4    Bob   23    Male        CSE     78          85    Chennai
4          5   Emma   21  Female        ECE     88          90  Hyderabad

In [28]:
print(data.head(2))

   StudentID   Name  Age Gender Department  Marks  Attendance       City
0          1  Rohan   21   Male        CSE     90          95  Bangalore
1          2   John   22   Male        ECE     85          88     Mumbai

In [29]:
# tail() : This works like .head() but starts from last
data.tail(2)

   StudentID    Name  Age  Gender Department  Marks  Attendance    City
8          9  Olivia   22  Female        ECE     94          96  Mumbai
9         10    Noah   23    Male         ME     76          84   Delhi

In [30]:
data.tail()

   StudentID    Name  Age  Gender Department  Marks  Attendance       City
5          6   David   22    Male        CSE     92          97       Pune
6          7  Sophia   20  Female         ME     81          89    Kolkata
7          8    Liam   21    Male        CSE     87          93  Bangalore
8          9  Olivia   22  Female        ECE     94          96     Mumbai
9         10    Noah   23    Male         ME     76          84      Delhi

In [31]:
# info() : Which gives the information about the data / table.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Gender      10 non-null     object
 4   Department  10 non-null     object
 5   Marks       10 non-null     int64
 6   Attendance  10 non-null     int64
 7   City        10 non-null     object
dtypes: int64(4), object(4)
memory usage: 768.0+ bytes

# Cleaning of Data

In [37]:
import pandas as pd
data = pd.read_csv('students.csv')
print(data)

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       NaN
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [47]:
#  removing empty cells row
df1 = data.dropna(subset=['Date'])
print(df1)

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [56]:
# to fill the empty value.
df = pd.read_csv('students.csv')
print(df.fillna(True))

    Duration        Date  Pulse  Maxpulse Calories
0         60  2020/12/01    110       130    409.1
1         60  2020/12/02    117       145    479.0
2         60  2020/12/03    103       135    340.0
3         45  2020/12/04    109       175    282.4
4         45  2020/12/05    117       148    406.0
5         60  2020/12/06    102       127    300.0
6         60  2020/12/07    110       136    374.0
7        450  2020/12/08    104       134    253.3
8         30  2020/12/09    109       133    195.1
9         60  2020/12/10     98       124    269.0
10        60  2020/12/11    103       147    329.3
11        60  2020/12/12    100       120    250.7
12        60  2020/12/12    100       120    250.7
13        60  2020/12/13    106       128    345.3
14        60  2020/12/14    104       132    379.3
15        60  2020/12/15     98       123    275.0
16        60  2020/12/16     98       120    215.2
17        60  2020/12/17    100       120    300.0
18        45  2020/12/18     90       112     True
19        60  2020/12/19    103       123    323.0
20        45  2020/12/20     97       125    243.0
21        60  2020/12/21    108       131    364.2
22        45        True    100       119    282.0
23        60  2020/12/23    130       101    300.0
24        45  2020/12/24    105       132    246.0
25        60  2020/12/25    102       126    334.5
26        60  2020/12/26    100       120    250.0
27        60  2020/12/27     92       118    241.0
28        60  2020/12/28    103       132     True
29        60  2020/12/29    100       132    280.0
30        60  2020/12/30    102       129    380.3
31        60  2020/12/31     92       115    243.0

In [59]:
# replace specific column
df.fillna({'Calories':0})

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       0.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       0.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [66]:
#  Mean , median and mode
import pandas as pd
data = pd.read_csv('students.csv')

mean = data['Calories'].mean()
print(mean)
# print(data.fillna({'Calories':mean}))

mode = data['Calories'].mode()
print(mode)

median = data['Calories'].median()
print(median)

304.68
0    300.0
Name: Calories, dtype: float64
291.2

In [70]:
# To remove duplicated value. It'll print True for duplicated value or false for unique value
print(data.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool

In [73]:
#  drop duplicated value
print(data.drop_duplicates())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       NaN
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [79]:
#  To find the correlation
data.drop('Calories',axis=1,inplace=True)

In [86]:
data.drop('Date',axis=1,inplace=True)
print(data)

    Duration  Pulse  Maxpulse
0         60    110       130
1         60    117       145
2         60    103       135
3         45    109       175
4         45    117       148
5         60    102       127
6         60    110       136
7        450    104       134
8         30    109       133
9         60     98       124
10        60    103       147
11        60    100       120
12        60    100       120
13        60    106       128
14        60    104       132
15        60     98       123
16        60     98       120
17        60    100       120
18        45     90       112
19        60    103       123
20        45     97       125
21        60    108       131
22        45    100       119
23        60    130       101
24        45    105       132
25        60    102       126
26        60    100       120
27        60     92       118
28        60    103       132
29        60    100       132
30        60    102       129
31        60     92       115

In [87]:
#  axis = 0 : which applies to row
#  axis = 1: which applies to column
# inplace=True : Which modifies the existing DataFrame
# inplace=False : returns new DataFrame

In [88]:
data.corr()

          Duration     Pulse  Maxpulse
Duration  1.000000  0.004410  0.049959
Pulse     0.004410  1.000000  0.276583
Maxpulse  0.049959  0.276583  1.000000

# Plotting

In [99]:
data = {
    1:[99,22],
    2:[92,36]
}

df= pd.DataFrame(data)
print(df.corr())

     1    2
1  1.0  1.0
2  1.0  1.0